### ISSUE TITLE
Cannot find source file: aulib_export.h

### ISSUE THREAD

**Issue by glebm** [realnc/SDL_audiolib#2]
I tried adding SDL_audiolib to DevilutionX CMake in https://github.com/glebm/devilutionX/commit/8d61cac1928133d581bd9c70c1823aeb80528b1e but got the following error:

```
CMake Error at build-sdl-audiolib/_deps/sdl_audiolib-src/CMakeLists.txt:293 (add_library):
  Cannot find source file:

    /home/gleb/devilutionX/build-sdl-audiolib/aulib_export.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc

```

**Comment by realnc** [comment]
That's a generated file. CMake needs to be ran first to generate it.

**Comment by glebm** [comment]
This error is the output of CMake, here is the CI run:

https://github.com/glebm/devilutionX/runs/2417059111

**Comment by glebm** [comment]
Fixed by https://github.com/realnc/SDL_audiolib/commit/ea5ca1605f71256f9294a0300ed201b033ac5da9

**Comment by ildar** [comment]
I still see this error on the current master.
I think that https://github.com/realnc/SDL_audiolib/blob/master/CMakeLists.txt#L202 is wrong if this library is used as a subproject. Please correct me if I'm wrong: I'm not a CMake expert.

**Comment by glebm** [comment]
This is how we use it as a subproject with no issues:
https://github.com/diasurgical/devilutionX/blob/master/3rdParty/SDL_audiolib/CMakeLists.txt

**Comment by ildar** [comment]
the problem shows up if you replace this `3rdParty/SDL_audiolib` with the
copy of the  `SDL_audiolib`.
Again, I'm not a CMake expert.
P.S. similar replacing of e.g. `3rdParty/simpleini` just works

**Comment by glebm** [comment]
Perhaps it should be `CMAKE_CURRENT_BINARY_DIR` rather than `CMAKE_BINARY_DIR`
